// Comprehensive list of countries for the contact form select box
// Each country has an English name and Arabic name for bilingual support

const countries = [
  { en: 'Afghanistan', ar: 'أفغانستان' },
  { en: 'Albania', ar: 'ألبانيا' },
  { en: 'Algeria', ar: 'الجزائر' },
  { en: 'Andorra', ar: 'أندورا' },
  { en: 'Angola', ar: 'أنغولا' },
  { en: 'Argentina', ar: 'الأرجنتين' },
  { en: 'Armenia', ar: 'أرمينيا' },
  { en: 'Australia', ar: 'أستراليا' },
  { en: 'Austria', ar: 'النمسا' },
  { en: 'Azerbaijan', ar: 'أذربيجان' },
  { en: 'Bahrain', ar: 'البحرين' },
  { en: 'Bangladesh', ar: 'بنغلاديش' },
  { en: 'Belarus', ar: 'بيلاروسيا' },
  { en: 'Belgium', ar: 'بلجيكا' },
  { en: 'Benin', ar: 'بنين' },
  { en: 'Bolivia', ar: 'بوليفيا' },
  { en: 'Bosnia and Herzegovina', ar: 'البوسنة والهرسك' },
  { en: 'Brazil', ar: 'البرازيل' },
  { en: 'Brunei', ar: 'بروناي' },
  { en: 'Bulgaria', ar: 'بلغاريا' },
  { en: 'Burkina Faso', ar: 'بوركينا فاسو' },
  { en: 'Cambodia', ar: 'كمبوديا' },
  { en: 'Cameroon', ar: 'الكاميرون' },
  { en: 'Canada', ar: 'كندا' },
  { en: 'Chad', ar: 'تشاد' },
  { en: 'Chile', ar: 'تشيلي' },
  { en: 'China', ar: 'الصين' },
  { en: 'Colombia', ar: 'كولومبيا' },
  { en: 'Comoros', ar: 'جزر القمر' },
  { en: 'Congo', ar: 'الكونغو' },
  { en: 'Costa Rica', ar: 'كوستاريكا' },
  { en: 'Croatia', ar: 'كرواتيا' },
  { en: 'Cuba', ar: 'كوبا' },
  { en: 'Cyprus', ar: 'قبرص' },
  { en: 'Czech Republic', ar: 'التشيك' },
  { en: 'Denmark', ar: 'الدنمارك' },
  { en: 'Djibouti', ar: 'جيبوتي' },
  { en: 'Dominican Republic', ar: 'جمهورية الدومينيكان' },
  { en: 'Ecuador', ar: 'الإكوادور' },
  { en: 'Egypt', ar: 'مصر' },
  { en: 'El Salvador', ar: 'السلفادور' },
  { en: 'Eritrea', ar: 'إريتريا' },
  { en: 'Estonia', ar: 'إستونيا' },
  { en: 'Ethiopia', ar: 'إثيوبيا' },
  { en: 'Finland', ar: 'فنلندا' },
  { en: 'France', ar: 'فرنسا' },
  { en: 'Gabon', ar: 'الغابون' },
  { en: 'Gambia', ar: 'غامبيا' },
  { en: 'Georgia', ar: 'جورجيا' },
  { en: 'Germany', ar: 'ألمانيا' },
  { en: 'Ghana', ar: 'غانا' },
  { en: 'Greece', ar: 'اليونان' },
  { en: 'Guatemala', ar: 'غواتيمالا' },
  { en: 'Guinea', ar: 'غينيا' },
  { en: 'Haiti', ar: 'هايتي' },
  { en: 'Honduras', ar: 'هندوراس' },
  { en: 'Hungary', ar: 'المجر' },
  { en: 'Iceland', ar: 'أيسلندا' },
  { en: 'India', ar: 'الهند' },
  { en: 'Indonesia', ar: 'إندونيسيا' },
  { en: 'Iran', ar: 'إيران' },
  { en: 'Iraq', ar: 'العراق' },
  { en: 'Ireland', ar: 'أيرلندا' },
  { en: 'Italy', ar: 'إيطاليا' },
  { en: 'Ivory Coast', ar: 'ساحل العاج' },
  { en: 'Jamaica', ar: 'جامايكا' },
  { en: 'Japan', ar: 'اليابان' },
  { en: 'Jordan', ar: 'الأردن' },
  { en: 'Kazakhstan', ar: 'كازاخستان' },
  { en: 'Kenya', ar: 'كينيا' },
  { en: 'Kuwait', ar: 'الكويت' },
  { en: 'Kyrgyzstan', ar: 'قيرغيزستان' },
  { en: 'Laos', ar: 'لاوس' },
  { en: 'Latvia', ar: 'لاتفيا' },
  { en: 'Lebanon', ar: 'لبنان' },
  { en: 'Libya', ar: 'ليبيا' },
  { en: 'Lithuania', ar: 'ليتوانيا' },
  { en: 'Luxembourg', ar: 'لوكسمبورغ' },
  { en: 'Madagascar', ar: 'مدغشقر' },
  { en: 'Malawi', ar: 'مالاوي' },
  { en: 'Malaysia', ar: 'ماليزيا' },
  { en: 'Maldives', ar: 'المالديف' },
  { en: 'Mali', ar: 'مالي' },
  { en: 'Malta', ar: 'مالطا' },
  { en: 'Mauritania', ar: 'موريتانيا' },
  { en: 'Mauritius', ar: 'موريشيوس' },
  { en: 'Mexico', ar: 'المكسيك' },
  { en: 'Moldova', ar: 'مولدوفا' },
  { en: 'Mongolia', ar: 'منغوليا' },
  { en: 'Montenegro', ar: 'الجبل الأسود' },
  { en: 'Morocco', ar: 'المغرب' },
  { en: 'Mozambique', ar: 'موزمبيق' },
  { en: 'Myanmar', ar: 'ميانمار' },
  { en: 'Namibia', ar: 'ناميبيا' },
  { en: 'Nepal', ar: 'نيبال' },
  { en: 'Netherlands', ar: 'هولندا' },
  { en: 'New Zealand', ar: 'نيوزيلندا' },
  { en: 'Nicaragua', ar: 'نيكاراغوا' },
  { en: 'Niger', ar: 'النيجر' },
  { en: 'Nigeria', ar: 'نيجيريا' },
  { en: 'North Macedonia', ar: 'مقدونيا الشمالية' },
  { en: 'Norway', ar: 'النرويج' },
  { en: 'Oman', ar: 'عُمان' },
  { en: 'Pakistan', ar: 'باكستان' },
  { en: 'Palestine', ar: 'فلسطين' },
  { en: 'Panama', ar: 'بنما' },
  { en: 'Paraguay', ar: 'باراغواي' },
  { en: 'Peru', ar: 'بيرو' },
  { en: 'Philippines', ar: 'الفلبين' },
  { en: 'Poland', ar: 'بولندا' },
  { en: 'Portugal', ar: 'البرتغال' },
  { en: 'Qatar', ar: 'قطر' },
  { en: 'Romania', ar: 'رومانيا' },
  { en: 'Russia', ar: 'روسيا' },
  { en: 'Rwanda', ar: 'رواندا' },
  { en: 'Saudi Arabia', ar: 'المملكة العربية السعودية' },
  { en: 'Senegal', ar: 'السنغال' },
  { en: 'Serbia', ar: 'صربيا' },
  { en: 'Sierra Leone', ar: 'سيراليون' },
  { en: 'Singapore', ar: 'سنغافورة' },
  { en: 'Slovakia', ar: 'سلوفاكيا' },
  { en: 'Slovenia', ar: 'سلوفينيا' },
  { en: 'Somalia', ar: 'الصومال' },
  { en: 'South Africa', ar: 'جنوب أفريقيا' },
  { en: 'South Korea', ar: 'كوريا الجنوبية' },
  { en: 'South Sudan', ar: 'جنوب السودان' },
  { en: 'Spain', ar: 'إسبانيا' },
  { en: 'Sri Lanka', ar: 'سريلانكا' },
  { en: 'Sudan', ar: 'السودان' },
  { en: 'Sweden', ar: 'السويد' },
  { en: 'Switzerland', ar: 'سويسرا' },
  { en: 'Syria', ar: 'سوريا' },
  { en: 'Taiwan', ar: 'تايوان' },
  { en: 'Tajikistan', ar: 'طاجيكستان' },
  { en: 'Tanzania', ar: 'تنزانيا' },
  { en: 'Thailand', ar: 'تايلاند' },
  { en: 'Togo', ar: 'توغو' },
  { en: 'Tunisia', ar: 'تونس' },
  { en: 'Turkey', ar: 'تركيا' },
  { en: 'Turkmenistan', ar: 'تركمانستان' },
  { en: 'UAE', ar: 'الإمارات العربية المتحدة' },
  { en: 'Uganda', ar: 'أوغندا' },
  { en: 'Ukraine', ar: 'أوكرانيا' },
  { en: 'United Kingdom', ar: 'المملكة المتحدة' },
  { en: 'United States', ar: 'الولايات المتحدة' },
  { en: 'Uruguay', ar: 'الأوروغواي' },
  { en: 'Uzbekistan', ar: 'أوزبكستان' },
  { en: 'Venezuela', ar: 'فنزويلا' },
  { en: 'Vietnam', ar: 'فيتنام' },
  { en: 'Yemen', ar: 'اليمن' },
  { en: 'Zambia', ar: 'زامبيا' },
  { en: 'Zimbabwe', ar: 'زيمبابوي' },
  { en: 'Other', ar: 'أخرى' },
];

export default countries;
